name = "ookscraft"
author = "ooks"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdf6554009849473efd98587ca5a612f9c082c35b1aa6f479f87ac3a8b2d4ee3"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
