name = "ookscraft"
author = "ooks"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c8718ee2eac0c052d31bf98b98282c0db1a3dd286bd30d782d9bbe408a4c517"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
