name = "ookscraft"
author = "ooks"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f74015a143f79db332b9308beba743b8b50e66e6feb0e5759df17117ac57a54c"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
