name = "ookscraft"
author = "ooks"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f20aaf13469ca1611856d90e6dbc0eb0202806fb1d58a0b22302a11624e550a"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
