name: Create modrith modpack release
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Build mrpack
        run: |
          OUTPUT_PATH=$(nix build .#mrpack --print-out-paths)
          echo "OUTPUT_PATH=$OUTPUT_PATH" >> $GITHUB_ENV
      - name: Publish mrpack
        uses: softprops/action-gh-release@v2
        with:
          files: "${{ env.OUTPUT_PATH }}/*"

