name: Create modrith modpack release
on:
  workflow_dispatch:
  push:
    tags:
     - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Build mrpack
        run: |
          OUTPUT_PATH=$(nix build .#mrpack --print-out-paths)
          echo "OUTPUT_PATH=$OUTPUT_PATH" >> $GITHUB_ENV
      - name: Publish mrpack
        uses: softprops/action-gh-release@v2
        with:
          files: "${{ env.OUTPUT_PATH }}/*"
  update-readme:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - name: Get previous tag
        id: previousTag
        run: echo "tag=$(git tag --sort=-creatordate | head -n 2 | tail -n 1)" >> $GITHUB_OUTPUT 
      - name: Update README
        run: |
          sed -i "s|${{ steps.previousTag.outputs.tag }}|${{ github.ref_name }}|g" README.md
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'README.md'
          message: 'Update README for release ${{ github.ref_name }}'


